### ISSUE TITLE
Version 0.2.1 shows no translations in pane

### ISSUE THREAD

**Issue by afduggirala** [ychoi-kr/omegat-plugin-deepl-api-free#10]
Hello.

I have tried loading the plugin by putting it in the plugins folder, the log says it was loaded correctly and I have also passed the API key option when launching OmegaT. However, I see no translations in the pane, no text is shown.

I'm on OmegaT version 6.0.1, although I think I also tested on v 6.1.

thank you,

**Comment by ychoi-kr** [comment]
I built a test JAR that should fix the issue.
Since GitHub doesn’t allow direct JAR uploads, I’ve renamed it to .zip.
Please download the attached file, rename it back to .jar, and put it in your plugins/ folder.
Let me know if translations now appear correctly on Linux. Thanks!

[omegat-plugin-deepl-api-free-0.2.2-SNAPSHOT.zip](https://github.com/user-attachments/files/22442762/omegat-plugin-deepl-api-free-0.2.2-SNAPSHOT.zip)

**Comment by afduggirala** [comment]
I have tried with the new version you linked, I am still not seeing any translations. 

46550: Info: Event: new entry activated (LOG_INFO_EVENT_ENTRY_ACTIVATED)
46550: FINER: Time for find matches: 33 
46550: Error: Uncatched exception in thread [Thread-120] 
46550: Error: java.lang.NoClassDefFoundError: org/json/JSONObject 
46550: Error: 	at kr.ychoi.otplugin.DeepLAPIFree.translate(DeepLAPIFree.java:84) 
46550: Error: 	at org.omegat.core.machinetranslators.BaseCachedTranslate.getTranslation(BaseCachedTranslate.java:118) 
46550: Error: 	at org.omegat.gui.exttrans.MachineTranslateTextArea$FindThread.getTranslation(MachineTranslateTextArea.java:275) 
46550: Error: 	at org.omegat.gui.exttrans.MachineTranslateTextArea$FindThread.search(MachineTranslateTextArea.java:258) 
46550: Error: 	at org.omegat.gui.exttrans.MachineTranslateTextArea$FindThread.search(MachineTranslateTextArea.java:233) 
46550: Error: 	at org.omegat.gui.common.EntryInfoSearchThread.run(EntryInfoSearchThread.java:96) 


FYI, I have tried with version 0.2.1 and 0.2.2 in OmegaT 6.1.0, in this case the plugin does not appear to be loaded. The deepl-api-free entry does not appear in the list of Machine Translation engines.

thank you,

**Comment by ychoi-kr** [comment]
Thanks for reporting. At the moment I'm evaluating the new official [DeepL connector plugin](https://github.com/omegat-org/deepl-connector-plugin) maintained under the OmegaT project.
Depending on how well it works, this plugin may be discontinued in favor of contributing directly to the official one.
I’ll update the status after further testing.

**Comment by ychoi-kr** [comment]
I submitted a [pull request](https://github.com/omegat-org/deepl-connector-plugin/pull/57) to the official OmegaT DeepL connector project ([omegat-org/deepl-connector-plugin](https://github.com/omegat-org/deepl-connector-plugin)) to support the V2 API. Hopefully, this update could also resolve the problem you are seeing.  

If you’re comfortable building from source, you can try the PR branch with the OmegaT Weekly Build (6.1.0 or later). Otherwise, the best option is to wait until the PR is reviewed and merged, after which an official release should become available.  

For transparency: this project is no longer being maintained, so future fixes will be happening in the official repo.
